config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    match '/scrape', to: 'articles#scrape', via: :post, on: :collection
  end

  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	self.per_page = 20
end

app/models/article_spider.rb
require "mechanize" # as of this writing, the latest release is 2.7.4

class ArticleSpider
  def self.process(url)
    pages_count = 140
    loop do
      agent = Mechanize.new
      page = agent.get(url + "?paging=#{pages_count}")
      articles = page.xpath("//div[@class='flex flex-row loop-item']")
      break if articles.blank?
      if articles.present?
        articles.each do |article|
          item = {}

          item[:title] = article.css('div.flex-grow').text.squish rescue ""
          item[:image_link] = article.css('a.loop-item__thumbnail-link img')[0]['src'] rescue ""
          item[:news_page_link] = article.css('div.loop-item__content a')[0]['href'] rescue ""

          Article.where(item).first_or_create
          pages_count = pages_count + 1
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  def scrape
    url = 'https://www.freethink.com/articles/'
    response = ScraperService.process(url)
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Articles scraping Done." }
      format.json { head :no_content }
    end
  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page])
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :image_link, :news_page_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Image link:</strong>
    <%= article.image_link %>
  </p>

  <p>
    <strong>News page link:</strong>
    <%= article.news_page_link %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image_link, style: "display: block" %>
    <%= form.text_field :image_link %>
  </div>

  <div>
    <%= form.label :news_page_link, style: "display: block" %>
    <%= form.text_field :news_page_link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<h2 style="color: green"><%= notice %></h2>
<%= button_to 'Scrape', scrape_articles_path %>
<%= link_to 'View Json', articles_path(format: :json) %>
<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

<%= will_paginate @posts %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/scrape.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<%= link_to "Back", root_path %>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kathascraper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>